/**
 * @Company     : Testing Systems.
 * @Description :
 * ****************************************************************************************
 * This class supports API operations in /createOrders/*. The methods currently supported are:
 *
 * 1. POST createOrdersFromPayload: This operation creates a new Account, Contact and Opportunity 
 * from the external payload.
 *
 * ****************************************************************************************
 * @History     :  Created on Nov 4, 2017 by Amit Tamse //Mostly the GIT path
 */
public class OrderProcessingConstant {
    
    //  ------------------------------------------------------------------------------------------------------------------
    //  Constants- Order constants
    //  ------------------------------------------------------------------------------------------------------------------
 
	public final String CREATE_NEW_ORDERS = 'ORDER_CREATE';
}