/**
 * @Company     : Testing Systems.
 * @Description :
 * ****************************************************************************************
 * OrderProcessingConstant  
 *
 * ****************************************************************************************
 * @History     :  Created on Nov 4, 2017 by Amit Tamse //Mostly the GIT path
 */
public class OrderProcessingConstant {
    
    //  ------------------------------------------------------------------------------------------------------------------
    //  Constants- Order constants
    //  ------------------------------------------------------------------------------------------------------------------
 
	public final String CREATE_NEW_ORDERS = 'ORDER_CREATE';
}
